---
title: "Diversity Through Inclusivity"
description: |
  The Hayes Lab values all individuals and strives to build an equitable research environment to freely explore both science and ourselves.
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

We are committed to cultivating an inclusive lab culture and actively stand against prejudice. We value each member of our community, and discrimination against race, ethnicity, gender identity, sexual orientation, disability, socioeconomic status, age, religion, or other personal identifier will not be permitted. Furthermore, we will take actions to promote inclusivity in our lab but also in our broader communities including our department, school, and scientific community. We are explorers - we look into the unknown to make discovers about how the world works. Sometimes the unknown is in the brain of a mouse or a vessel of a human, and other times it is within ourselves. I aim to train people to be good scientists, but to be good humans first.


# My commitment to you

As a mentor, I commit to help your development as a scientist to formulate interesting questions and designing thoughful experiments to test your hypotheses. I will support the vision for your career and work together to provide opportunities toward achieving that goal, whatever direction that may be. I want students to be unburdened by what they think is possible and dare to dream big. 

I will help you prepare for your next adventure! My lab isn't the destination it is only a way-point on the path to your dreams. To accomplish this, I commit to help you prepare for conference presentations, qualifying exams, graduate school interviews, write recommendation letters, nominate you for awards, support funding applications, and advocate for your success to my peers.


# Your commitment to the lab

- I expect everyone to be treated with respect and dignity. The diverse perspective that each individual brings to discussions and brainstorming is viewed as a resource and benefit to our success as a lab. 

- I expect everyone to do their best to gracefully communicate with each other and myself to share resources, resolve conflicts, brainstorm ideas, troubleshoot problems, and identify personal goals. It is important that you can work independently and be a productive member of a team. This can only be achieved through open and honest communication and a willingness to hear feedback from others.

- I expect scientific integrity, hard work, and thoughtful execution. I expect every individual to understand what they are doing and why, and if you don't know, then ask! I expect you to show a passionate interest in your project and motivation to explore new questions and ideas. If you don't like what you're doing then we can work together to find the right environment for your goals. 
