---
title: "Publications"
description: | 
output: distill::distill_article
---

```{r, echo=FALSE, message=TRUE}
message( " updated on ", Sys.Date() )
```

[link to Pubmed Bibliography](https://www.ncbi.nlm.nih.gov/myncbi/lindsay.hayes.1/bibliography/public/)

[link to Google Scholar](https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AH70aAXHtXP8CmkpG-GLig5B4MzBvK0by1LYxI938UwQ9bMXwoYP-Mm-3H4uKPKaTF3R5UZ-ZP0aKe0LJ0ybcaYHbO5Y&user=xZ4hUFwAAAAJ)

1. **Hayes LN**, An K, Carloni E, Li F, Vincent E, Paranjpe M, Dolen G, Goff LA, Ramos A, Kano S, Sawa A (2022) Prenatal immune stress induces a prolonged blunting of microglia activation that impacts striatal connectivity. *Nature*, 610(7931):327-334 [link](https://www.nature.com/articles/s41586-022-05274-z)

1. Ramos A, Ishizuka K, Namkung H, **Hayes LN**, Saito A, Sengupta A, Srivastava R, Calva C, Hayashida A, Elkins N, Palen T, Carloni E, Tsujimura T, Gallego JA, Robinson DG, Malhotra AK, Ikemoto S, Rais R, Slusher BS, Niwa M, Saitoh T, Takimoto E, Sawa A (2022) The nuclear GAPDH-HMBG cascade in cortical microglia regulates cognitive flexibility. *bioRxiv*, 2022.06.21.497065 [link](https://www.biorxiv.org/content/10.1101/2022.06.21.497065v3)

1.  **Hayes LN**, An K, Carloni E, Li F, Vincent E, Paranjpe M, Dolen G, Goff LA, Ramos A, Kano S, Sawa A (2021) Prenatal immune stress induces a prolonged blunting of microglia activation that impacts striatal connectivity. *bioRxiv*, 2021.12.27.473694. [link](https://www.biorxiv.org/content/10.1101/2021.12.27.473694v1)

2.  Carloni E, Ramos A, **Hayes LN** (2021) Developmental Stressors Induce Innate Immune Memory in Microglia and Contribute to Disease Risk. *International Journal of Molecular Sciences*, 22:13035. [link](https://www.mdpi.com/1422-0067/22/23/13035)

3.  Xiao MF, Roh SE, Zhou J, Chien CC, Lucey BP, Craig MT, **Hayes LN**, Coughlin JM, Leweke FM, Jia M, Xu D, Zhou W, Conover Talbot C, Arnold DB, Staley M, Jiang C, Reti IM, Sawa A, Pelkey KA, McBain CJ, Savonenko A et al. (2021) A biomarker-authenticated model of schizophrenia implicating NPTX2 loss of function. *Science Advances*, 7:eabf6935. [link](https://www.science.org/doi/10.1126/sciadv.abf6935?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed)

4.  Mueller FS, Richetto J, **Hayes LN**, Zambon A, Pollak DD, Sawa A, Meyer U, Weber-Stadlbauer U (2019) Influence of poly(I:C) variability on thermoregulation, immune responses and pregnancy outcomes in mouse models of maternal immune activation. *Brain Behavior Immunity*, 80:406--418. [link](https://www.sciencedirect.com/science/article/pii/S0889159119301217?via%3Dihub)

5.  Fukudome D, **Hayes LN\***, Faust TE\*, Foss CA, Kondo MA, Lee BJ, Saito A, Kano SI, Coughlin JM, Kamiya A, Pomper MG, Sawa A, Niwa M (2018) Translocator protein (TSPO) and stress cascades in mouse models of psychosis with inflammatory disturbances. *Schizophrenia Research*, 197:492-497. [link](https://www.sciencedirect.com/science/article/pii/S0920996418300355?via%3Dihub)

6.  Nucifora LG, Tanaka T, **Hayes LN**, Kim M, Lee BJ, Matsuda T, Nucifora FC, Sedlak T, Mojtabai R, Eaton W, Sawa A (2017) Reduction of plasma glutathione in psychosis associated with schizophrenia and bipolar disorder in translational psychiatry. *Translational Psychiatry*, 7:e1215. [link](https://www.nature.com/articles/tp2017178)

7.  Coughlin JM\*, **Hayes LN**\*, Tanaka T\*, Xiao M, Yolken RH, Worley P, Leweke FM, Sawa A (2017) Reduced superoxide dismutase-1 (SOD1) in cerebrospinal fluid of patients with early psychosis in association with clinical features. *Schizophrenia Research*, 183:64--69. [link](https://www.sciencedirect.com/science/article/pii/S0920996416304923?via%3Dihub)

8.  Tanaka T\*, Matsuda T\*, **Hayes LN**\*, Yang S, Rodriguez K, Severance EG, Yolken RH, Sawa A, Eaton WW (2017) Infection and inflammation in schizophrenia and bipolar disorder. *Neuroscience Research*, 115:59--63. [link](https://www.sciencedirect.com/science/article/pii/S0168010216302462?via%3Dihub)

9.  **Hayes LN\***, Shevelkin A\*, Zeledon M, Steel G, Chen PL, Obie C, Pulver A, Avramopoulos D, Valle D, Sawa A, Pletnikov MV (2016) Neuregulin 3 Knockout Mice Exhibit Behaviors Consistent with Psychotic Disorders. *Molecular Neuropsychiatry*, 2:79--87. [link](https://www.karger.com/Article/FullText/445836)

10. Coughlin JM, Wang Y, Ambinder EB, Ward RE, Minn I, Vranesic M, Kim PK, Ford CN, Higgs C, **Hayes LN**, Schretlen DJ, Dannals RF, Kassiou M, Sawa A, Pomper MG (2016) In vivo markers of inflammatory response in recent-onset schizophrenia: a combined study using [(11)C]DPA-713 PET and analysis of CSF and plasma. *Translational Psychiatry*, 6:e777. [link](https://www.nature.com/articles/tp201640)

11. **Hayes LN**, Severance EG, Leek JT, Gressitt KL, Rohleder C, Coughlin JM, Leweke FM, Yolken RH, Sawa A (2014) Inflammatory molecular signature associated with infectious agents in psychosis. *Schizophrenia Bulletin*, 40:963--972. [link](https://academic.oup.com/schizophreniabulletin/article/40/5/963/2886795)

12. **Hayes LN**, Ralls S, Wang H, Ahn S (2013) Duration of Shh signaling contributes to mDA neuron diversity. *Developmental Biology*, 374:115--126. [link](https://www.sciencedirect.com/science/article/pii/S0012160612006355?via%3Dihub)

13. **Hayes LN**, Zhang Z, Albert P, Zervas M, Ahn S (2011) Timing of Sonic hedgehog and Gli1 expression segregates midbrain dopamine neurons. *Journal of Comparative Neurology*, 519:3001--3018. [link](https://onlinelibrary.wiley.com/doi/10.1002/cne.22711)

14. Brown A, Machan JT, **Hayes LN**, Zervas M (2011) Molecular organization and timing of Wnt1 expression define cohorts of midbrain dopamine neuron progenitors in vivo. *Journal of Comparative Neurology*, 519:2978--3000. [link](https://onlinelibrary.wiley.com/doi/10.1002/cne.22710)

15. Carney RS, Mangin JM, **Hayes LN**, Mansfield K, Sousa VH, Fishell G, Machold RP, Ahn S, Gallo V, Corbin JG (2010) Sonic hedgehog expressing and responding cells generate neuronal diversity in the medial amygdala. *Neural Development*, 5:14. [link](https://neuraldevelopment.biomedcentral.com/articles/10.1186/1749-8104-5-14)

16. Devore M, **Foresee LN**, Michno N, Badger S (2006) Determination of Environmental Conditions of Four Greene County Caves. *Transactions of the Missouri Academy of Science*, 40:22--29. [link](https://www.moacademysci.org/wp-content/uploads/2017/01/Transactions40-2006.pdf)

17. Li K, **Foresee LN**, Tunge JA (2005) Trifluoroacetic acid-mediated hydroarylation: synthesis of dihydrocoumarins and dihydroquinolones. *Journal of Organic Chemistry*, 70:2881--2883. [link](https://pubs.acs.org/doi/10.1021/jo0477650)

18. Tunge JA, **Foresee LN** (2005) Mechanistic Studies of Fujiwara Hydroarylation. C− H Activation versus Electrophilic Aromatic Substitution. *Organometallics*, 24:6440--6444. [link](https://pubs.acs.org/doi/10.1021/om0507225)
